@startuml rdcu-redemarrerJeu
title RDCU pour redemarrerJeu

participant ":JeuDeDes" as jeu
participant "joueurs: Map<String, Joueur>" as joueurs

-> jeu : redemarrerJeu()
note right
selon Contrôleur
(JeuDeDés est l'objet racine)
end note

jeu -> joueurs : clear()
note right
selon Expert
end note

@enduml
